#!/usr/bin/env python3
"""
emit_slab_80_140.py
===================

Emit a Lean proof of SlabSimplePolyIneq for the [80, 140] slab,
using the template `slabSimplePolyIneq_of_const_cloud_and_analytic_tail`
and a 50-zero rational K-bound.
"""
import math
from pathlib import Path
from fractions import Fraction
import mpmath as mp


def riemann_zeros_50(prec=40):
    mp.mp.dps = prec + 5
    return [mp.im(mp.zetazero(k)) for k in range(1, 51)]


def main():
    zeros = riemann_zeros_50()
    # Upper bounds at 4 decimal precision
    zeros_up = [Fraction(math.ceil(float(g) * 10000), 10000) for g in zeros]

    # Slab [80, 140]:  Tmax/2 - 1 = 69, x_max² + y_max² = 9522.
    x_max = Fraction(69)
    xy_sq = x_max * x_max + x_max * x_max  # 9522

    # K_lb = Σ 1/(9522 + γ_up²) for 50 zeros.
    K_lb = sum(Fraction(1, 1) / (xy_sq + g * g) for g in zeros_up)
    print(f"K_lb = {K_lb} ≈ {float(K_lb)}")
    print(f"K_lb 2*K_lb = {float(2 * K_lb)}")
    print(f"Needed at T=80: 2K ≥ {0.01268 - 0.00742} ≈ 0.00526 → K ≥ 0.00263")
    print(f"Slack: 2*K_lb - 0.00526 ≈ {float(2*K_lb) - 0.00526}")

    # Emit Lean. Use Fraction → "a / b" rationals.
    lines = ["-- Auto-generated by emit_slab_80_140.py",
             "-- Per-zero upper bounds (rational, 4-decimal precision)",
             "noncomputable def gammaUp50 : List ℝ := ["]
    for i, g in enumerate(zeros_up, 1):
        sep = "," if i < 50 else ""
        # Use simple decimal form (since Lean ℝ accepts decimals)
        lines.append(f"  ({g.numerator} : ℝ) / {g.denominator}{sep}  -- γ_{i}")
    lines.append("]")
    lines.append("")
    lines.append(f"-- K_lower_bound: {K_lb.numerator} / {K_lb.denominator}")
    lines.append(f"--             ≈ {float(K_lb)}")
    lines.append(f"-- Needed: K ≥ 0.00263 (at T=80, slab [80,140], C=1/2, D=49/20)")

    out = Path(__file__).parent / "slab_80_140_data.lean"
    out.write_text("\n".join(lines))
    print(f"\nWrote {out}")
    print(f"\nFirst few list entries:")
    for i in range(3):
        print(f"  γ_{i+1} = {zeros_up[i]} = {float(zeros_up[i])}")


if __name__ == "__main__":
    main()
