"""
SCHUR ALGORITHM attack on Theta_Phi.

The Schur algorithm: a function f holomorphic on the disk D with |f|<=1 (a Schur
function) has Schur parameters gamma_0, gamma_1, ... with |gamma_n|<=1, generated by
   f_0 = f,  gamma_n = f_n(0),  f_{n+1}(z) = (1/z) (f_n(z)-gamma_n)/(1-conj(gamma_n) f_n(z)).
CONVERSELY |gamma_n|<=1 for all n  <=>  f is Schur (contractive).  So if we can show
the Schur parameters of Theta_Phi stay in the disk for a STRUCTURAL reason tied to the
theta coefficients, that proves contractivity.

We map the UHP to the disk by w = (z-i)/(z+i) (z in UHP <-> w in D), and form
   f(w) = Theta_Phi(z(w)),  z(w) = i(1+w)/(1-w).
Then run the Schur algorithm on the Taylor coefficients of f at w=0 (i.e. z=i, the
center of the UHP) and watch |gamma_n|.

Theta_Phi(z) = B(z)/A(z) where (from the established identity, with C(w)=Xi(w)/2):
   A+B = 2 C(x-iy),  A-B = -2i C'(x-iy), so at a point z=x+iy:
   A = C(w) - i C'(w),  B = C(w) + i C'(w)? -- let's just use the EXACT transforms.
Actually simplest & rigorous: use Theta_Phi = B/A computed directly from the moment
integrals L1..L4 (matching ScratchHBDominance EXACTLY), as a function of z=x+iy.

We compute Theta as an analytic function of z in the UHP, get its Taylor series at
z=i via mpmath.taylor of f(w), and run Schur.  The DECISIVE question: are the
gamma_n forced into the disk by theta structure, or do they exit (|gamma_n|>1) unless
RH?  Since Theta is unimodular on the boundary R, f is unimodular on |w|=1, so f is
INNER iff Schur (all |gamma_n|<=1) iff Blaschke/singular-inner -- which is again the
zero-location = RH.  We test numerically with the TRUE Phi to see the gamma_n.
"""
import mpmath as mp
mp.mp.dps = 18

def phi_term(u,n):
    npi=mp.pi*n*n
    return (2*npi*npi*mp.e**(9*u)-3*npi*mp.e**(5*u))*mp.e**(-npi*mp.e**(4*u))
def Phi(u,N=18): return mp.fsum(phi_term(u,n) for n in range(1,N+1))
UP=5.0

# Exact A,B transforms (ScratchHBDominance conventions) as analytic fn of z=x+iy.
# A = L1+iL3, B=L2+iL4 with L's the moment integrals. These are real-analytic in (x,y)
# but A,B as functions of z=x+iy are NOT holomorphic individually; however the RATIO
# Theta=B/A equals (via the closed form) an HONEST holomorphic function of z. Use the
# closed form: A+B=2C(conj? ) ... use the verified identity from hb_dominance_verdict:
#   A+B = 2 C(w),  A-B = -2i C'(w),  w = x - i y = conj(z).
# So A = C(w) - i C'(w),  B = C(w) + i C'(w),  with w=conj(z).  Then
#   Theta(z) = B/A = (C(w)+iC'(w))/(C(w)-iC'(w)),  w=conj(z).
# As a function of w (LHP since Im w=-y<0) this is HOLOMORPHIC in w. Map LHP->disk.
def C(w):  return mp.quad(lambda u:Phi(u)*mp.cos(w*u),[0,UP])
def Cp(w): return mp.quad(lambda u:-Phi(u)*u*mp.sin(w*u),[0,UP])
def Theta_w(w):
    c=C(w); cp=Cp(w)
    return (c+1j*cp)/(c-1j*cp)

# w in LHP (Im w<0).  Map disk D -> LHP:  w(t) = -i (1+t)/(1-t)?  center t=0 -> w=-i.
# Check: t=0 -> w=-i (Im=-1<0 good). |t|<1 -> LHP. boundary |t|=1 -> R.
def w_of_t(t): return -1j*(1+t)/(1-t)
def f_of_t(t): return Theta_w(w_of_t(t))

print("Taylor coefficients of f(t)=Theta(w(t)) at t=0 (center w=-i in LHP):")
# mpmath taylor needs a function of one complex var; use numerical derivatives.
Ncoef=7
coeffs = mp.taylor(f_of_t, 0, Ncoef)
for k,c in enumerate(coeffs):
    print(f"  a[{k}] = {mp.nstr(c,8)}  |a[{k}]|={mp.nstr(abs(c),6)}")

print()
print("SCHUR ALGORITHM on f (as power series a[0]+a[1]t+...):  gamma_n and |gamma_n|")
def schur_params(a):
    # a: list of Taylor coeffs of a Schur function; returns gamma_n
    a=[mp.mpc(x) for x in a]
    gammas=[]
    for n in range(len(a)-1):
        g=a[0]
        gammas.append(g)
        if abs(1-abs(g)**2)<1e-18:
            break
        # f_{n+1} = (1/t)(f_n - g)/(1 - conj(g) f_n); update truncated power series
        # series division. Represent f_n by coeffs a. Compute (f_n-g) and (1-conj(g)f_n).
        num=[a[0]-g]+a[1:]
        den=[1-mp.conj(g)*a[0]]+[-mp.conj(g)*c for c in a[1:]]
        # divide num/den as power series
        q=[mp.mpf(0)]*len(num)
        for i in range(len(num)):
            s=num[i]-sum(q[j]*den[i-j] for j in range(i))
            q[i]=s/den[0]
        # divide by t: drop constant (should be ~0), shift
        a=q[1:]+[mp.mpf(0)]
    return gammas

gam=schur_params(coeffs)
maxabs=0
for n,g in enumerate(gam):
    ag=abs(g); maxabs=max(maxabs,float(ag))
    flag="" if ag<=1+1e-9 else "  <-- |gamma|>1  NOT SCHUR"
    print(f"  gamma[{n}] = {mp.nstr(g,6):>22}  |gamma|={mp.nstr(ag,6)}{flag}")
print(f"\nmax |gamma_n| = {maxabs:.8f}   => {'all in disk (Schur-consistent)' if maxabs<=1+1e-6 else 'EXITS DISK'}")
print()
print("INTERPRETATION: Theta is unimodular on R, so f is inner on the disk iff it is")
print("Schur (|gamma_n|<=1 all n). With the TRUE Phi (zeros real numerically) it is")
print("Schur. The structural question: do theta coefficients FORCE |gamma_n|<=1 WITHOUT")
print("assuming the zeros are real?  See schur_structural_test.py for the falsification.")
